name: Linting

on: [push]

jobs:
  pronto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: eregon/use-ruby-action@master #this will use by default the .ruby-version file in the repository
      - name: Install Pronto
        run: gem install --no-document rubocop:0.78.0 faraday:0.17.0 pronto pronto-rubocop pronto-flay pronto-brakeman pronto-rails_best_practices pronto-rails_schema pronto-reek pronto-scss
      - name: Run Pronto
        env:
          PRONTO_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          git fetch --unshallow
          SHA=$(jq --raw-output .head_commit.id "${GITHUB_EVENT_PATH}")
          OWNER=$(jq --raw-output .repository.owner.name "${GITHUB_EVENT_PATH}")
          REPO=$(jq --raw-output .repository.name "${GITHUB_EVENT_PATH}")
          HEAD_COMMIT_PULLS_URL="https://api.github.com/repos/${OWNER}/${REPO}/commits/${SHA}/pulls"
          PULL_IDS=$(curl -H "Accept: application/vnd.github.groot-preview+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $HEAD_COMMIT_PULLS_URL | jq --raw-output .[].number)

          if [ -z "${PULL_IDS}" ]; then
            echo "No pull request found, bailing out"
            exit 0
          else
            echo "Running pronto for ${PULL_IDS}"
          fi

          for PULL_ID in $PULL_IDS; do
            PRONTO_PULL_REQUEST_ID=${PULL_ID} pronto run -f github_status github_pr -c origin/master
          done

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint
